
server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: replace_me
    password: replace_me
    url: jdbc:mysql://localhost:3306/REPLACE_ME?userLegacyDatetimeCode=false
